spring:
  datasource:
    url: jdbc:postgresql://192.168.1.99:26257/burp_betting?sslmode=disable
  flyway:
    placeholders:
      cdc-sink-url: kafka://192.168.1.99:9092
  kafka:
    bootstrap-servers: 192.168.1.99:9092
app:
  customer-api-url: http://localhost:8090/api
