spring:
  datasource:
    url: jdbc:postgresql://localhost:26257/customer?sslmode=disable
  flyway:
    placeholders:
      cdc-sink-url: kafka://localhost:9092
  kafka:
    bootstrap-servers: localhost:9092